- name: install keepalived
  yum: name=keepalived state=present

- name: set net.ipv4.ip_nonlocal_bind to 1
  sysctl: name=net.ipv4.ip_nonlocal_bind value=1 state=present

- name: put keepalived.conf
  template: src=keepalived.conf dest=/etc/keepalived/keepalived.conf backup=yes

- name: enable and start keepalived
  service: name=keepalived enabled=yes state=started
